In [577]:
import sys
!{sys.executable} -m pip install auto-sklearn

  Using cached https://files.pythonhosted.org/packages/c3/c6/c555cfa3c7d0078dded091d4901ed52344bbb925077aa70b871faf35fd58/pyrfr-0.7.4.tar.gz
  Stored in directory: /home/subramanyat/.cache/pip/wheels/fb/98/fd/b1d53cab6d5ed836980777d9733d7e549d82a727650eed6f6d
Successfully built pyrfr


In [346]:
import xgboost

In [2]:
import pandas as pd
import numpy as np

In [81]:
train_data = pd.read_excel("Data_Train.xlsx")

In [82]:
train_data.head()

Name    Location  Year  Kilometers_Driven  \
0            Maruti Wagon R LXI CNG      Mumbai  2010              72000   
1  Hyundai Creta 1.6 CRDi SX Option        Pune  2015              41000   
2                      Honda Jazz V     Chennai  2011              46000   
3                 Maruti Ertiga VDI     Chennai  2012              87000   
4   Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013              40670   

  Fuel_Type Transmission Owner_Type     Mileage   Engine      Power  Seats  \
0       CNG       Manual      First  26.6 km/kg   998 CC  58.16 bhp    5.0   
1    Diesel       Manual      First  19.67 kmpl  1582 CC  126.2 bhp    5.0   
2    Petrol       Manual      First   18.2 kmpl  1199 CC   88.7 bhp    5.0   
3    Diesel       Manual      First  20.77 kmpl  1248 CC  88.76 bhp    7.0   
4    Diesel    Automatic     Second   15.2 kmpl  1968 CC  140.8 bhp    5.0   

   New_Price  Price  
0        NaN   1.75  
1        NaN  12.50  
2  8.61 Lakh   4.50  
3        NaN   6.00  
4        NaN  17.74

In [83]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 13 columns):
Name                 6019 non-null object
Location             6019 non-null object
Year                 6019 non-null int64
Kilometers_Driven    6019 non-null int64
Fuel_Type            6019 non-null object
Transmission         6019 non-null object
Owner_Type           6019 non-null object
Mileage              6017 non-null object
Engine               5983 non-null object
Power                5983 non-null object
Seats                5977 non-null float64
New_Price            824 non-null object
Price                6019 non-null float64
dtypes: float64(2), int64(2), object(9)
memory usage: 611.4+ KB


In [154]:
train_data_processed = train_data.copy()

In [84]:
train_data.Name.unique().shape

(1876,)

In [125]:
train_data_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 14 columns):
Name                 6019 non-null object
Location             6019 non-null object
Year                 6019 non-null int64
Kilometers_Driven    6019 non-null int64
Fuel_Type            6019 non-null object
Transmission         6019 non-null object
Owner_Type           6019 non-null object
Mileage              6017 non-null object
Engine               5983 non-null object
Power                5983 non-null object
Seats                6019 non-null category
New_Price            824 non-null object
Price                6019 non-null float64
No_Years             6019 non-null int64
dtypes: category(1), float64(1), int64(3), object(9)
memory usage: 617.6+ KB


#         Car FirstName 

In [120]:
Car_FirstName = []
for i in range(train_data.shape[0]):
    name = train_data.iloc[i].Name
    Car_FirstName.append(name.split(' ')[0])

In [122]:
set(Car_FirstName)

{'Ambassador',
 'Audi',
 'BMW',
 'Bentley',
 'Chevrolet',
 'Datsun',
 'Fiat',
 'Force',
 'Ford',
 'Honda',
 'Hyundai',
 'ISUZU',
 'Isuzu',
 'Jaguar',
 'Jeep',
 'Lamborghini',
 'Land',
 'Mahindra',
 'Maruti',
 'Mercedes-Benz',
 'Mini',
 'Mitsubishi',
 'Nissan',
 'Porsche',
 'Renault',
 'Skoda',
 'Smart',
 'Tata',
 'Toyota',
 'Volkswagen',
 'Volvo'}

In [123]:
len(set(Car_FirstName))

31

In [116]:
train_data.Name.iloc[2].split(' ')[0]

'Honda'

#                   Location

In [10]:
train_data.Location.unique()

array(['Mumbai', 'Pune', 'Chennai', 'Coimbatore', 'Hyderabad', 'Jaipur',
       'Kochi', 'Kolkata', 'Delhi', 'Bangalore', 'Ahmedabad'],
      dtype=object)

In [119]:
train_data.Location.unique().shape

(11,)

In [11]:
train_data.Location.value_counts()

Mumbai        790
Hyderabad     742
Kochi         651
Coimbatore    636
Pune          622
Delhi         554
Kolkata       535
Chennai       494
Jaipur        413
Bangalore     358
Ahmedabad     224
Name: Location, dtype: int64

#  Year 

In [12]:
train_data.Year.unique()

array([2010, 2015, 2011, 2012, 2013, 2016, 2018, 2014, 2017, 2007, 2009,
       2008, 2019, 2006, 2005, 2004, 2002, 2000, 2003, 1999, 2001, 1998])

In [13]:
train_data.Year.unique().shape

(22,)

In [93]:
train_data['No_Years'] = 2020 - train_data.Year

In [95]:
train_data['No_Years'].describe()

count    6019.000000
mean        6.641801
std         3.269742
min         1.000000
25%         4.000000
50%         6.000000
75%         9.000000
max        22.000000
Name: No_Years, dtype: float64

# Kilometers_Driven

In [15]:
train_data.Kilometers_Driven.unique().shape

(3093,)

In [16]:
train_data.Kilometers_Driven.describe()

count    6.019000e+03
mean     5.873838e+04
std      9.126884e+04
min      1.710000e+02
25%      3.400000e+04
50%      5.300000e+04
75%      7.300000e+04
max      6.500000e+06
Name: Kilometers_Driven, dtype: float64

# Fuel_Type

In [17]:
train_data.Fuel_Type.unique()

array(['CNG', 'Diesel', 'Petrol', 'LPG', 'Electric'], dtype=object)

In [18]:
train_data.Fuel_Type.value_counts()

Diesel      3205
Petrol      2746
CNG           56
LPG           10
Electric       2
Name: Fuel_Type, dtype: int64

In [107]:
train_data[train_data.Fuel_Type == 'Electric']

Name Location  Year  Kilometers_Driven Fuel_Type  \
4446       Mahindra E Verito D4  Chennai  2016              50000  Electric   
4904  Toyota Prius 2009-2016 Z4   Mumbai  2011              44000  Electric   

     Transmission Owner_Type Mileage   Engine   Power Seats   New_Price  \
4446    Automatic      First     NaN    72 CC  41 bhp   5.0  13.58 Lakh   
4904    Automatic      First     NaN  1798 CC  73 bhp   5.0         NaN   

      Price  No_Years  
4446  13.00         4  
4904  12.75         9

#   Transmission

In [19]:
train_data.Transmission.value_counts()

Manual       4299
Automatic    1720
Name: Transmission, dtype: int64

# Owner_Type

In [20]:
train_data.Owner_Type.value_counts()

First             4929
Second             968
Third              113
Fourth & Above       9
Name: Owner_Type, dtype: int64

# Mileage

In [31]:
mileage_value = train_data.Mileage.apply(lambda x : float(str(x).split(' ')[0]))

In [229]:
mileage_value_test = test_data.Mileage.apply(lambda x : float(str(x).split(' ')[0]))

In [29]:
train_data.Mileage.iloc[14]

'0.0 kmpl'

In [30]:
train_data.iloc[14]

Name                 Land Rover Freelander 2 TD4 SE
Location                                       Pune
Year                                           2012
Kilometers_Driven                             85000
Fuel_Type                                    Diesel
Transmission                              Automatic
Owner_Type                                   Second
Mileage                                    0.0 kmpl
Engine                                      2179 CC
Power                                       115 bhp
Seats                                             5
New_Price                                       NaN
Price                                          17.5
Name: 14, dtype: object

In [34]:
 mileage_units = train_data.Mileage.apply(lambda x : str(x).split(' ')[1])

IndexError: list index out of range

In [33]:
train_data.Mileage.iloc[10].split(' ')[1]

'kmpl'

In [36]:
mileage_units = []
for i in range(train_data.Mileage.shape[0]):
    try:
        mileage_units.append(train_data.Mileage.iloc[i].split(' ')[1])   
    except:
        mileage_units.append('NA')
        print(i)

4446
4904


In [37]:
train_data.Mileage.

nan

In [38]:
len(mileage_units)

6019

In [39]:
len(mileage_value)

6019

In [40]:
mileage_value[4446]

nan

In [41]:
mileage_value[4904]

nan

In [42]:
mileage_units = pd.Series(mileage_units)

In [43]:
mileage_units.value_counts()

kmpl     5951
km/kg      66
NA          2
dtype: int64

In [96]:
mileage_units.shape

(6019,)

In [130]:
len(mileage_value)

6019

In [44]:
mileage_value = pd.Series(mileage_value)

In [45]:
mileage_value.describe()

count    6017.000000
mean       18.134961
std         4.582289
min         0.000000
25%        15.170000
50%        18.150000
75%        21.100000
max        33.540000
Name: Mileage, dtype: float64

In [99]:
mileage = list(zip(mileage_value,mileage_units))

In [100]:
len(mileage)

6019

In [ ]:
mileage_value

In [104]:
fuel_type = []
for i in range(len(mileage)):
    if mileage[i][1] == 'km/kg':
        fuel_type.append(train_data.iloc[i].Fuel_Type)
        

In [105]:
len(fuel_type)

66

In [106]:
set(fuel_type)

{'CNG', 'LPG'}

In [155]:
train_data_processed.Mileage = mileage_value

In [231]:
test_data.Mileage = mileage_value_test

In [ ]:
prices = {'CNG' = 40, 'Diesel' = , 'Petrol' = , 'LPG' = }

# Engine 

In [48]:
engine_units = []
for i in range(train_data.Engine.shape[0]):
    try:
        engine_units.append(train_data.Engine.iloc[i].split(' ')[1])   
    except:
        engine_units.append('NA')
        #print(i)

In [49]:
engine_units = pd.Series(engine_units)

In [50]:
engine_units.value_counts()

CC    5983
NA      36
dtype: int64

In [52]:
engine_value = train_data.Engine.apply(lambda x : float(str(x).split(' ')[0]))

In [236]:
engine_value_test = test_data.Engine.apply(lambda x : float(str(x).split(' ')[0]))

In [54]:
engine_value.describe()

count    5983.000000
mean     1621.276450
std       601.355233
min        72.000000
25%      1198.000000
50%      1493.000000
75%      1984.000000
max      5998.000000
Name: Engine, dtype: float64

In [156]:
train_data_processed['Engine'] = pd.Series(engine_value)

In [238]:
test_data['Engine'] = pd.Series(engine_value_test)

In [157]:
train_data_processed.Engine.describe()

count    5983.000000
mean     1621.276450
std       601.355233
min        72.000000
25%      1198.000000
50%      1493.000000
75%      1984.000000
max      5998.000000
Name: Engine, dtype: float64

#               Power

In [55]:
power_units = []
for i in range(train_data.Power.shape[0]):
    try:
        power_units.append(train_data.Power.iloc[i].split(' ')[1])   
    except:
        power_units.append('NA')

In [57]:
set(power_units)

{'NA', 'bhp'}

In [59]:
power_value = train_data.Power.apply(lambda x : str(x).split(' ')[0])

In [232]:
power_value_test = test_data.Power.apply(lambda x : str(x).split(' ')[0])

In [242]:
pd.Series(power_value_test).head()

0     58.2
1     47.3
2    147.8
3     null
4    82.85
Name: Power, dtype: object

In [60]:
power_value.describe()

count     6019
unique     373
top         74
freq       235
Name: Power, dtype: object

In [67]:
for i in range(len(power_value)):
    if power_value[i] == 'null':
        power_value[i] = np.nan     

In [243]:
for i in range(len(power_value_test)):
    if power_value_test[i] == 'null':
        power_value_test[i] = np.nan  

In [68]:
power_value = pd.Series(power_value).astype(float)

In [244]:
power_value_test = pd.Series(power_value_test).astype(float)

In [245]:
test_data['Power'] = pd.Series(power_value_test)

In [162]:
train_data_processed['Power'] = pd.Series(power_value)

In [167]:
train_data_processed.describe()

Year  Kilometers_Driven      Mileage       Engine        Power  \
count  6019.000000       6.019000e+03  6018.000000  6019.000000  6019.000000   
mean   2013.358199       5.873838e+04    18.146903  1620.551088   112.938182   
std       3.269742       9.126884e+04     4.674620   599.626796    53.269277   
min    1998.000000       1.710000e+02     0.000000    72.000000    34.200000   
25%    2011.000000       3.400000e+04    15.170000  1198.000000    78.000000   
50%    2014.000000       5.300000e+04    18.155000  1493.000000    98.600000   
75%    2016.000000       7.300000e+04    21.100000  1969.000000   138.030000   
max    2019.000000       6.500000e+06    90.000000  5998.000000   560.000000   

             Price     No_Years  
count  6019.000000  6019.000000  
mean      9.479468     6.641801  
std      11.187917     3.269742  
min       0.440000     1.000000  
25%       3.500000     4.000000  
50%       5.640000     6.000000  
75%       9.950000     9.000000  
max     160.000000    22.000000

In [69]:
power_value.describe()

count    5876.000000
mean      113.253050
std        53.874957
min        34.200000
25%        75.000000
50%        97.700000
75%       138.100000
max       560.000000
Name: Power, dtype: float64

# Missing Value Imputation    Power - 100 (mostly near to median)

In [166]:
train_data_processed['Power'] = train_data_processed['Power'].fillna(100.0)

In [70]:
pd.isnull(power_value).sum()

143

In [72]:
train_data.Seats.unique()

array([ 5.,  7.,  8.,  4.,  6.,  2., nan, 10.,  9.,  0.])

In [73]:
train_data.Seats.value_counts()

5.0     5014
7.0      674
8.0      134
4.0       99
6.0       31
2.0       16
10.0       5
9.0        3
0.0        1
Name: Seats, dtype: int64

In [74]:
pd.isnull(train_data.Seats).sum()

42

In [75]:
train_data.Seats.unique().shape

(10,)

# Missing Value Imputation

Nan's are converted to 0.0 assuming cars with Seat = 0.0 are actually Nan's

In [85]:
train_data.Seats = train_data.Seats.fillna(0.0)

In [86]:
train_data.Seats.value_counts()

5.0     5014
7.0      674
8.0      134
4.0       99
0.0       43
6.0       31
2.0       16
10.0       5
9.0        3
Name: Seats, dtype: int64

In [87]:
type(train_data.Seats)

pandas.core.series.Series

In [88]:
type(train_data.Seats.iloc[0])

numpy.float64

In [89]:
train_data.Seats = train_data.Seats.astype('category')

In [90]:
train_data.Seats.value_counts()

5.0     5014
7.0      674
8.0      134
4.0       99
0.0       43
6.0       31
2.0       16
10.0       5
9.0        3
Name: Seats, dtype: int64

In [91]:
target = train_data.Price

In [92]:
target.describe()

count    6019.000000
mean        9.479468
std        11.187917
min         0.440000
25%         3.500000
50%         5.640000
75%         9.950000
max       160.000000
Name: Price, dtype: float64

In [133]:
train_data_processed[train_data_processed.Mileage == 0]

Name    Location  Year  \
14                  Land Rover Freelander 2 TD4 SE        Pune  2012   
67        Mercedes-Benz C-Class Progressive C 220d  Coimbatore  2019   
79                          Hyundai Santro Xing XL   Hyderabad  2005   
194                             Honda City 1.5 GXI   Ahmedabad  2007   
229                               Ford Figo Diesel   Bangalore  2015   
262                         Hyundai Santro Xing XL   Hyderabad  2006   
307                         Hyundai Santro Xing XL     Chennai  2006   
424           Volkswagen Jetta 2007-2011 1.9 L TDI   Hyderabad  2010   
443                  Hyundai Santro GLS I - Euro I  Coimbatore  2012   
544    Mercedes-Benz New C-Class Progressive C 200       Kochi  2019   
631                      Hyundai Santro LS zipPlus     Chennai  2002   
647                         Hyundai Santro Xing XP      Jaipur  2004   
707            Mercedes-Benz M-Class ML 350 4Matic        Pune  2014   
749                   Land Rover Range Rover 3.0 D      Mumbai  2008   
915                            Smart Fortwo CDI AT        Pune  2008   
962       Mercedes-Benz C-Class Progressive C 220d      Mumbai  2018   
996                         Hyundai Santro Xing GL        Pune  2008   
1059                        Hyundai Santro Xing GL   Hyderabad  2010   
1259                 Land Rover Freelander 2 TD4 S   Bangalore  2010   
1271                Hyundai Santro GLS I - Euro II      Jaipur  2009   
1308           Mercedes-Benz M-Class ML 350 4Matic   Bangalore  2014   
1345                             Maruti Baleno Vxi        Pune  2005   
1354                        Hyundai Santro Xing GL       Kochi  2011   
1385                            Honda City 1.5 GXI        Pune  2004   
1419                        Hyundai Santro Xing XL     Chennai  2007   
1460  Land Rover Range Rover Sport 2005 2012 Sport  Coimbatore  2008   
1764           Mercedes-Benz M-Class ML 350 4Matic        Pune  2015   
1857                             Hyundai Santro DX   Hyderabad  2007   
2053                       Mahindra Jeep MM 550 PE   Hyderabad  2009   
2096                     Hyundai Santro LP zipPlus  Coimbatore  2004   
...                                            ...         ...   ...   
3033                        Hyundai Santro Xing XP      Jaipur  2005   
3044                        Hyundai Santro Xing GL     Kolkata  2009   
3061                             Hyundai Santro GS   Ahmedabad  2005   
3093                   Audi A7 2011-2015 Sportback     Kolkata  2012   
3189          Hyundai Santro GS zipDrive - Euro II     Chennai  2002   
3210           Mercedes-Benz M-Class ML 350 4Matic  Coimbatore  2016   
3271                        Hyundai Santro Xing GL   Bangalore  2008   
3516                 Hyundai Santro GLS I - Euro I        Pune  2011   
3522               Hyundai Santro GLS II - Euro II       Kochi  2012   
3645                        Hyundai Santro Xing XP   Bangalore  2004   
4152                  Land Rover Range Rover 3.0 D      Mumbai  2003   
4234           Mercedes-Benz M-Class ML 350 4Matic     Chennai  2012   
4302                        Hyundai Santro Xing GL       Delhi  2012   
4412           Mercedes-Benz M-Class ML 350 4Matic  Coimbatore  2016   
4629                            Fiat Siena 1.2 ELX      Jaipur  2001   
4687                Land Rover Freelander 2 TD4 SE      Jaipur  2012   
4704           Mercedes-Benz M-Class ML 350 4Matic   Bangalore  2015   
5016               Land Rover Freelander 2 TD4 HSE       Delhi  2013   
5022                Land Rover Freelander 2 TD4 SE   Hyderabad  2013   
5119                        Hyundai Santro Xing XP     Kolkata  2008   
5270                            Honda City 1.5 GXI   Bangalore  2002   
5311                Land Rover Freelander 2 TD4 SE   Hyderabad  2012   
5374           Mercedes-Benz M-Class ML 350 4Matic   Ahmedabad  2012   
5426                        Hyundai Santro Xing XL     Chennai  2006   
5529          

In [168]:
train_data_processed[pd.isnull(train_data_processed.Mileage)]

Name Location  Year  Kilometers_Driven Fuel_Type  \
4904  Toyota Prius 2009-2016 Z4   Mumbai  2011              44000  Electric   

     Transmission Owner_Type  Mileage  Engine  Power Seats New_Price  Price  \
4904    Automatic      First      NaN  1798.0   73.0   5.0       NaN  12.75   

      No_Years  
4904         9

In [136]:
(426.0/90)*19

89.93333333333334

In [158]:
train_data_processed['Mileage'].iloc[4446] = 90.0

In [170]:
train_data_processed['Mileage'].iloc[4904] = 50.0

In [159]:
train_data_processed.iloc[4446]

Name                 Mahindra E Verito D4
Location                          Chennai
Year                                 2016
Kilometers_Driven                   50000
Fuel_Type                        Electric
Transmission                    Automatic
Owner_Type                          First
Mileage                                90
Engine                                 72
Power                              41 bhp
Seats                                   5
New_Price                      13.58 Lakh
Price                                  13
No_Years                                4
Name: 4446, dtype: object

# Power  

In [145]:
train_data_processed[pd.isnull(train_data_processed.Power)]

Name    Location  Year  \
76                   Ford Fiesta 1.4 SXi TDCi      Jaipur  2008   
79                     Hyundai Santro Xing XL   Hyderabad  2005   
89                     Hyundai Santro Xing XO   Hyderabad  2007   
120      Hyundai Santro Xing XL eRLX Euro III      Mumbai  2005   
143       Hyundai Santro Xing XO eRLX Euro II       Kochi  2008   
194                        Honda City 1.5 GXI   Ahmedabad  2007   
208                      Maruti Swift 1.3 VXi     Kolkata  2010   
227                     Maruti Swift VDI BSIV       Delhi  2013   
245       Hyundai Santro Xing XO eRLX Euro II      Mumbai  2007   
262                    Hyundai Santro Xing XL   Hyderabad  2006   
307                    Hyundai Santro Xing XL     Chennai  2006   
308                     Maruti Swift VDI BSIV     Kolkata  2011   
386      Hyundai Santro Xing XL eRLX Euro III   Hyderabad  2007   
424      Volkswagen Jetta 2007-2011 1.9 L TDI   Hyderabad  2010   
428       Hyundai Santro Xing XO eRLX Euro II        Pune  2006   
443             Hyundai Santro GLS I - Euro I  Coimbatore  2012   
472           Ford Fiesta 1.6 SXI ABS Duratec     Chennai  2009   
575                    Hyundai Santro Xing XO     Chennai  2006   
631                 Hyundai Santro LS zipPlus     Chennai  2002   
647                    Hyundai Santro Xing XP      Jaipur  2004   
648                           Tata Indica DLS      Jaipur  2009   
733                      Maruti Swift 1.3 VXi     Chennai  2006   
739                     Maruti Swift VDI BSIV   Bangalore  2007   
748                    Hyundai Santro Xing XO   Hyderabad  2007   
749              Land Rover Range Rover 3.0 D      Mumbai  2008   
829                       Toyota Etios Liva G      Mumbai  2012   
915                       Smart Fortwo CDI AT        Pune  2008   
926                Porsche Cayman 2009-2012 S   Hyderabad  2010   
934                           Toyota Etios GD     Kolkata  2012   
1068                     Toyota Etios Liva GD        Pune  2012   
...                                       ...         ...   ...   
4697                   Fiat Punto 1.2 Dynamic       Kochi  2017   
4709                           Maruti 1000 AC   Hyderabad  1998   
4712                   Hyundai Santro Xing XG        Pune  2003   
4714            Mercedes-Benz E-Class 220 CDI   Ahmedabad  2011   
4744     Hyundai Santro Xing XL eRLX Euro III     Kolkata  2005   
4830                        Maruti Esteem Vxi     Chennai  2004   
4886   Hyundai Santro Xing XL AT eRLX Euro II   Hyderabad  2007   
4900  Hyundai Santro Xing XL AT eRLX Euro III   Hyderabad  2007   
4952                   Fiat Punto 1.4 Emotion     Kolkata  2010   
4954                     Toyota Etios Liva GD  Coimbatore  2013   
5015                     Maruti Swift 1.3 VXi       Delhi  2006   
5065              Maruti Swift VDI BSIV W ABS   Hyderabad  2016   
5119                   Hyundai Santro Xing XP     Kolkata  2008   
5185                     Maruti Swift 1.3 LXI       Delhi  2012   
5228     Hyundai Santro Xing XL eRLX Euro III        Pune  2005   
5270                       Honda City 1.5 GXI   Bangalore  2002   
5426                   Hyundai Santro Xing XL     Chennai  2006   
5438              Ford Endeavour XLT TDCi 4X4      Mumbai  2007   
5458                    Maruti Swift VDI BSIV   Hyderabad  2014   
5529              Hyundai Santro LP - Euro II     Chennai  2005   
5533      Hyundai Santro Xing XO eRLX Euro II        Pune  2007   
5647                   Toyota Qualis Fleet A3      Mumbai  2001   
5755     Hyundai Santro Xing XL eRLX Euro III   Ahmedabad  2008   
5759     Hyundai Santro Xing XL eRLX Euro III     Kolkata  2007   
5861                   Hyundai Santro Xing XO     Chennai  2007   
5873      Hyundai Santro Xing XO eRLX Euro II        Pune  2006   
5893                        Maruti Estilo LXI     Chennai  2008   
5925              Skoda Laura Classic 1.8 TSI        Pune  2010   
5943                 

In [169]:
train_data_processed.Engine.describe()

count    6019.000000
mean     1620.551088
std       599.626796
min        72.000000
25%      1198.000000
50%      1493.000000
75%      1969.000000
max      5998.000000
Name: Engine, dtype: float64

#  Engine Imputation  - 1500

In [160]:
train_data_processed.Engine = train_data_processed.Engine.fillna(1500.0)

In [171]:
train_data_processed.describe()

Year  Kilometers_Driven      Mileage       Engine        Power  \
count  6019.000000       6.019000e+03  6019.000000  6019.000000  6019.000000   
mean   2013.358199       5.873838e+04    18.152195  1620.551088   112.938182   
std       3.269742       9.126884e+04     4.692229   599.626796    53.269277   
min    1998.000000       1.710000e+02     0.000000    72.000000    34.200000   
25%    2011.000000       3.400000e+04    15.170000  1198.000000    78.000000   
50%    2014.000000       5.300000e+04    18.160000  1493.000000    98.600000   
75%    2016.000000       7.300000e+04    21.100000  1969.000000   138.030000   
max    2019.000000       6.500000e+06    90.000000  5998.000000   560.000000   

             Price     No_Years  
count  6019.000000  6019.000000  
mean      9.479468     6.641801  
std      11.187917     3.269742  
min       0.440000     1.000000  
25%       3.500000     4.000000  
50%       5.640000     6.000000  
75%       9.950000     9.000000  
max     160.000000    22.000000

In [172]:
train_data_processed.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price', 'No_Years'],
      dtype='object')

In [173]:
target = train_data_processed.Price

In [176]:
train_data_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 14 columns):
Name                 6019 non-null object
Location             6019 non-null object
Year                 6019 non-null category
Kilometers_Driven    6019 non-null int64
Fuel_Type            6019 non-null object
Transmission         6019 non-null object
Owner_Type           6019 non-null object
Mileage              6019 non-null float64
Engine               6019 non-null float64
Power                6019 non-null float64
Seats                6019 non-null category
New_Price            824 non-null object
Price                6019 non-null float64
No_Years             6019 non-null int64
dtypes: category(2), float64(4), int64(2), object(6)
memory usage: 577.3+ KB


In [175]:
train_data_processed.Year = train_data_processed.Year.astype('category')

In [177]:
input_columns = ['Location', 'Year', 'Kilometers_Driven', 'Fuel_Type','Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats', 'No_Years']

In [178]:
len(input_columns)

11

In [179]:
train_data_input = train_data_processed[input_columns]

In [180]:
train_data_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 11 columns):
Location             6019 non-null object
Year                 6019 non-null category
Kilometers_Driven    6019 non-null int64
Fuel_Type            6019 non-null object
Transmission         6019 non-null object
Owner_Type           6019 non-null object
Mileage              6019 non-null float64
Engine               6019 non-null float64
Power                6019 non-null float64
Seats                6019 non-null category
No_Years             6019 non-null int64
dtypes: category(2), float64(3), int64(2), object(4)
memory usage: 436.2+ KB


In [181]:
train_data_input_encoded = pd.get_dummies(train_data_input)

In [182]:
train_data_input_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 58 columns):
Kilometers_Driven            6019 non-null int64
Mileage                      6019 non-null float64
Engine                       6019 non-null float64
Power                        6019 non-null float64
No_Years                     6019 non-null int64
Location_Ahmedabad           6019 non-null uint8
Location_Bangalore           6019 non-null uint8
Location_Chennai             6019 non-null uint8
Location_Coimbatore          6019 non-null uint8
Location_Delhi               6019 non-null uint8
Location_Hyderabad           6019 non-null uint8
Location_Jaipur              6019 non-null uint8
Location_Kochi               6019 non-null uint8
Location_Kolkata             6019 non-null uint8
Location_Mumbai              6019 non-null uint8
Location_Pune                6019 non-null uint8
Year_1998                    6019 non-null uint8
Year_1999                    6019 non-null uint8
Year_

#     Modelling and Cross Validation

In [183]:
from sklearn.model_selection import cross_val_score

In [184]:
from sklearn.linear_model import LinearRegression

In [188]:
linear_reg = LinearRegression()

In [189]:
scores = cross_val_score(linear_reg, train_data_input_encoded.values, target.values, cv=5)

In [190]:
scores

array([0.72646339, 0.53274613, 0.72352835, 0.65983148, 0.76815087])

In [191]:
np.mean(scores)

0.6821440431724892

In [192]:
type(scores)

numpy.ndarray

# Model without Pre-processing 

In [193]:
model_reg_1 = linear_reg.fit(train_data_input_encoded.values, target.values)

In [194]:
# Predicting on Test data 

In [195]:
test_data = pd.read_excel("Data_Test.xlsx")

In [248]:
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 13 columns):
Name                 1234 non-null object
Location             1234 non-null object
Year                 1234 non-null category
Kilometers_Driven    1234 non-null int64
Fuel_Type            1234 non-null object
Transmission         1234 non-null object
Owner_Type           1234 non-null object
Mileage              1234 non-null float64
Engine               1234 non-null float64
Power                1234 non-null float64
Seats                1234 non-null category
New_Price            182 non-null object
No_Years             1234 non-null int64
dtypes: category(2), float64(3), int64(2), object(6)
memory usage: 109.7+ KB


#      Missing Values

In [197]:
test_data.Engine = test_data.Engine.fillna(1500.0)

In [247]:
test_data.Power = test_data.Power.fillna(100.0)

In [209]:
test_data.Seats = test_data.Seats.astype('category')

In [208]:
test_data.Seats.value_counts()

5.0     1033
7.0      122
8.0       36
4.0       20
0.0       11
6.0        7
10.0       3
2.0        2
Name: Seats, dtype: int64

In [207]:
test_data.Seats = test_data.Seats.fillna('0.0')

In [211]:
test_data['No_Years'] = 2020 - test_data.Year

In [212]:
test_data['Year'] = test_data['Year'].astype('category')

In [249]:
test_data_input = test_data[input_columns]

In [250]:
test_data_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 11 columns):
Location             1234 non-null object
Year                 1234 non-null category
Kilometers_Driven    1234 non-null int64
Fuel_Type            1234 non-null object
Transmission         1234 non-null object
Owner_Type           1234 non-null object
Mileage              1234 non-null float64
Engine               1234 non-null float64
Power                1234 non-null float64
Seats                1234 non-null category
No_Years             1234 non-null int64
dtypes: category(2), float64(3), int64(2), object(4)
memory usage: 90.4+ KB


In [253]:
test_data_input['Test'] = True

/home/subramanyat/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [251]:
test_data_input.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 11 columns):
Location             1234 non-null object
Year                 1234 non-null category
Kilometers_Driven    1234 non-null int64
Fuel_Type            1234 non-null object
Transmission         1234 non-null object
Owner_Type           1234 non-null object
Mileage              1234 non-null float64
Engine               1234 non-null float64
Power                1234 non-null float64
Seats                1234 non-null category
No_Years             1234 non-null int64
dtypes: category(2), float64(3), int64(2), object(4)
memory usage: 90.4+ KB


In [252]:
train_data_input['Test'] = False

/home/subramanyat/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [254]:
train_data_input.shape

(6019, 12)

In [255]:
train_data_input.columns == test_data_input.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [256]:
total_data_input = pd.concat([train_data_input,test_data_input])

In [257]:
total_data_input.shape

(7253, 12)

In [258]:
total_data_input.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7253 entries, 0 to 1233
Data columns (total 12 columns):
Location             7253 non-null object
Year                 7253 non-null int64
Kilometers_Driven    7253 non-null int64
Fuel_Type            7253 non-null object
Transmission         7253 non-null object
Owner_Type           7253 non-null object
Mileage              7253 non-null float64
Engine               7253 non-null float64
Power                7253 non-null float64
Seats                7253 non-null object
No_Years             7253 non-null int64
Test                 7253 non-null bool
dtypes: bool(1), float64(3), int64(3), object(5)
memory usage: 687.1+ KB


In [367]:
total_data_input.columns

Index(['Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Transmission',
       'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats', 'No_Years',
       'Test'],
      dtype='object')

In [259]:
total_data_input.Year = total_data_input.Year.astype('category')

In [260]:
total_data_input_encoded = pd.get_dummies(total_data_input)

In [261]:
total_data_input_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7253 entries, 0 to 1233
Data columns (total 61 columns):
Kilometers_Driven            7253 non-null int64
Mileage                      7253 non-null float64
Engine                       7253 non-null float64
Power                        7253 non-null float64
No_Years                     7253 non-null int64
Test                         7253 non-null bool
Location_Ahmedabad           7253 non-null uint8
Location_Bangalore           7253 non-null uint8
Location_Chennai             7253 non-null uint8
Location_Coimbatore          7253 non-null uint8
Location_Delhi               7253 non-null uint8
Location_Hyderabad           7253 non-null uint8
Location_Jaipur              7253 non-null uint8
Location_Kochi               7253 non-null uint8
Location_Kolkata             7253 non-null uint8
Location_Mumbai              7253 non-null uint8
Location_Pune                7253 non-null uint8
Year_1996                    7253 non-null uint8
Year_1

In [266]:
train_input_final = total_data_input_encoded[total_data_input_encoded.Test==False].drop('Test',axis=1)

In [273]:
test_input_final = total_data_input_encoded[total_data_input_encoded.Test==True].drop('Test',axis=1)

In [267]:
train_input_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6019 entries, 0 to 6018
Data columns (total 60 columns):
Kilometers_Driven            6019 non-null int64
Mileage                      6019 non-null float64
Engine                       6019 non-null float64
Power                        6019 non-null float64
No_Years                     6019 non-null int64
Location_Ahmedabad           6019 non-null uint8
Location_Bangalore           6019 non-null uint8
Location_Chennai             6019 non-null uint8
Location_Coimbatore          6019 non-null uint8
Location_Delhi               6019 non-null uint8
Location_Hyderabad           6019 non-null uint8
Location_Jaipur              6019 non-null uint8
Location_Kochi               6019 non-null uint8
Location_Kolkata             6019 non-null uint8
Location_Mumbai              6019 non-null uint8
Location_Pune                6019 non-null uint8
Year_1996                    6019 non-null uint8
Year_1998                    6019 non-null uint8
Year_

In [298]:
train_input_final.columns

Index(['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'No_Years',
       'Location_Ahmedabad', 'Location_Bangalore', 'Location_Chennai',
       'Location_Coimbatore', 'Location_Delhi', 'Location_Hyderabad',
       'Location_Jaipur', 'Location_Kochi', 'Location_Kolkata',
       'Location_Mumbai', 'Location_Pune', 'Year_1996', 'Year_1998',
       'Year_1999', 'Year_2000', 'Year_2001', 'Year_2002', 'Year_2003',
       'Year_2004', 'Year_2005', 'Year_2006', 'Year_2007', 'Year_2008',
       'Year_2009', 'Year_2010', 'Year_2011', 'Year_2012', 'Year_2013',
       'Year_2014', 'Year_2015', 'Year_2016', 'Year_2017', 'Year_2018',
       'Year_2019', 'Fuel_Type_CNG', 'Fuel_Type_Diesel', 'Fuel_Type_Electric',
       'Fuel_Type_LPG', 'Fuel_Type_Petrol', 'Transmission_Automatic',
       'Transmission_Manual', 'Owner_Type_First', 'Owner_Type_Fourth & Above',
       'Owner_Type_Second', 'Owner_Type_Third', 'Seats_0.0', 'Seats_2.0',
       'Seats_4.0', 'Seats_5.0', 'Seats_6.0', 'Seats_7.0', 'Seats_

In [299]:
year_columns = ['Year_1996', 'Year_1998',
       'Year_1999', 'Year_2000', 'Year_2001', 'Year_2002', 'Year_2003',
       'Year_2004', 'Year_2005', 'Year_2006', 'Year_2007', 'Year_2008',
       'Year_2009', 'Year_2010', 'Year_2011', 'Year_2012', 'Year_2013',
       'Year_2014', 'Year_2015', 'Year_2016', 'Year_2017', 'Year_2018',
       'Year_2019']

In [300]:
len(year_columns)

23

# Linear  Regression Model Proper 

In [270]:
scores = cross_val_score(linear_reg, train_input_final.values, target.values, cv=3)

In [271]:
scores

array([0.70244454, 0.59091667, 0.71920656])

In [272]:
reg_model = linear_reg.fit(train_input_final.values, target.values)

In [277]:
Price_predictions = pd.Series(reg_model.predict(test_input_final.values))

In [280]:
Predictions_final = pd.DataFrame()

In [466]:
Predictions_final['Price'] = Price_predictions

In [283]:
Predictions_final['Price'] = Predictions_final['Price'].apply(lambda x: x if x > 0 else 0)

In [285]:
Predictions_final.describe()

Price
count  1234.000000
mean      9.316807
std       8.745963
min       0.000000
25%       3.034553
50%       7.009940
75%      13.146416
max      71.925571

In [286]:
Predictions_final.to_excel("Submissions_Regression.xlsx")

#    Linear Regression with Target Log Transformed

In [287]:
price_logs = np.log(target.values)

In [289]:
scores = cross_val_score(linear_reg, train_input_final.values, price_logs, cv=5)

In [290]:
scores

array([0.88073218, 0.81446774, 0.86361923, 0.88447246, 0.88102505])

In [291]:
reg_model = linear_reg.fit(train_input_final.values, price_logs)

In [293]:
Price_predictions = pd.Series(np.exp(reg_model.predict(test_input_final.values)))

In [294]:
Price_predictions.describe()

count    1234.000000
mean        8.676774
std        13.055447
min         0.567755
25%         3.674490
50%         5.489788
75%         9.369013
max       348.425515
dtype: float64

In [467]:
Predictions_final = pd.DataFrame()

In [468]:
Predictions_final['Price'] = Price_predictions

In [469]:
Predictions_final.to_excel("Submissions_Regression_le.xlsx",index=False)

#  Linear Regression with Target Log Transformed and Year Removed 

In [304]:
columns_model3 = [col for col in list(train_input_final.columns) if col not in year_columns]

In [306]:
train_input_model3 = train_input_final[columns_model3]

In [311]:
test_input_model3 = test_input_final[columns_model3]

In [308]:
scores = cross_val_score(linear_reg, train_input_model3.values, price_logs, cv=5)

In [309]:
scores

array([0.87844525, 0.82134549, 0.8623644 , 0.88253422, 0.88005802])

In [310]:
reg_model = linear_reg.fit(train_input_model3.values, price_logs)

In [312]:
Price_predictions = pd.Series(np.exp(reg_model.predict(test_input_model3.values)))

In [313]:
Predictions_final = pd.DataFrame()

In [314]:
Predictions_final['Price'] = Price_predictions

In [315]:
Predictions_final.to_excel("Submissions_Regression_targetLog_Year_removed.xlsx",index=False)

#  Model 4 - Same as model 4 with Input Features Log Transformed 

In [332]:
train_input_model4 = train_input_model3.copy()

In [331]:
train_input_model3[ 'Mileage'].describe()

count    6019.000000
mean       18.355551
std         4.272321
min         6.400000
25%        15.400000
50%        18.160000
75%        21.100000
max        90.000000
Name: Mileage, dtype: float64

In [330]:
train_input_model3[ 'Mileage'] = train_input_model3[ 'Mileage'].replace(0.0,18.0)

/home/subramanyat/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [333]:
train_input_model4[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']] = train_input_model3[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']].apply(np.log)

In [334]:
train_input_model4[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']].describe() 

Kilometers_Driven      Mileage       Engine        Power
count        6019.000000  6019.000000  6019.000000  6019.000000
mean           10.758780     2.882821     7.330754     4.636770
std             0.715788     0.235456     0.339274     0.411507
min             5.141664     1.856298     4.276666     3.532226
25%            10.434116     2.734368     7.088409     4.356709
50%            10.878047     2.899221     7.308543     4.591071
75%            11.198215     3.049273     7.585281     4.927471
max            15.687313     4.499810     8.699181     6.327937

In [335]:
test_input_model3[ 'Mileage'] = test_input_model3[ 'Mileage'].replace(0.0,18.0)

/home/subramanyat/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [336]:
test_input_model4 = test_input_model3.copy()

In [337]:
test_input_model4[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']] = test_input_model3[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']].apply(np.log)

In [338]:
scores = cross_val_score(linear_reg, train_input_model4.values, price_logs, cv=5)

In [339]:
scores

array([0.89169547, 0.88230292, 0.87601332, 0.88585391, 0.88733507])

In [340]:
reg_model = linear_reg.fit(train_input_model4.values, price_logs)

In [341]:
Price_predictions = pd.Series(np.exp(reg_model.predict(test_input_model4.values)))

In [475]:
Predictions_final = pd.DataFrame()

In [476]:
Predictions_final['Price'] = Price_predictions

In [477]:
Predictions_final.to_excel("Submissions_Regression_le_latest.xlsx",index=False)

#    XGBoost Model 

In [347]:
model_xgb = xgboost.XGBRegressor(colsample_bytree=0.4,
                 gamma=0,                 
                 learning_rate=0.07,
                 max_depth=3,
                 min_child_weight=1.5,
                 n_estimators=500,                                                                    
                 reg_alpha=0.75,
                 reg_lambda=0.45,
                 subsample=0.6,
                 seed=42) 

In [348]:
scores = cross_val_score(model_xgb, train_input_model4.values, price_logs, cv=5)

[15:28:42] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[15:28:44] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[15:28:45] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[15:28:47] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[15:28:49] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [349]:
scores

array([0.93906404, 0.92947674, 0.92653311, 0.93520749, 0.93336767])

In [350]:
xgb_model = model_xgb.fit(train_input_model4.values, price_logs)

[15:30:24] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [351]:
Price_predictions = pd.Series(np.exp(xgb_model.predict(test_input_model4.values)))

In [546]:
Predictions_final = pd.DataFrame()

In [547]:
Predictions_final['Price'] = Price_predictions

In [548]:
Predictions_final.to_excel("Submissions_Regression_Model_le_7_42_noInf.xlsx",index=False)

#             XGB Model 2 

In [355]:
model_xgb_2 = xgboost.XGBRegressor()

In [356]:
scores = cross_val_score(model_xgb_2, train_input_model4.values, price_logs, cv=5)

[15:34:35] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[15:34:35] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[15:34:36] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[15:34:36] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[15:34:37] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [357]:
scores

array([0.92172576, 0.91077902, 0.90752039, 0.91763096, 0.91498621])

In [358]:
xgb_model = model_xgb_2.fit(train_input_model4.values, price_logs)

[15:35:15] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [359]:
Price_predictions = pd.Series(np.exp(xgb_model.predict(test_input_model4.values)))

# XGB Model 3  - with the data of Model 1 

In [364]:
model_xgb_3 = xgboost.XGBRegressor(colsample_bytree=0.4,
                 gamma=0,                 
                 learning_rate=0.07,
                 max_depth=3,
                 min_child_weight=1.5,
                 n_estimators=500,                                                                    
                 reg_alpha=0.75,
                 reg_lambda=0.45,
                 subsample=0.6,
                 seed=42) 

In [365]:
scores = cross_val_score(model_xgb_3, train_input_final.values, target.values, cv=5)

[16:33:24] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:33:26] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:33:28] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:33:30] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[16:33:32] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [366]:
scores 

array([0.90977836, 0.8907887 , 0.87961911, 0.8661071 , 0.86535765])

# XGB Model 4 - Label encoding

In [426]:
categorical_columns = ['Location', 'Fuel_Type', 'Transmission','Owner_Type', 'Seats']

In [427]:
numerical_columns = [col for col in list(total_data_input.columns) if col not in categorical_columns]

In [428]:
 numerical_columns.remove('Test')

In [430]:
 numerical_columns.remove('Year')

In [431]:
numerical_columns

['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'No_Years']

In [432]:
len(categorical_columns)

5

In [433]:
train_data_input['Seats'] = train_data_input['Seats'].replace('0.0',0.0)

/home/subramanyat/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [434]:
test_data_input['Seats'] = test_data_input['Seats'].replace('0.0',0.0)

/home/subramanyat/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [435]:
for i in range(len(categorical_columns)):
    print((train_data_input[categorical_columns[i]].value_counts().index))

Index(['Mumbai', 'Hyderabad', 'Kochi', 'Coimbatore', 'Pune', 'Delhi',
       'Kolkata', 'Chennai', 'Jaipur', 'Bangalore', 'Ahmedabad'],
      dtype='object')
Index(['Diesel', 'Petrol', 'CNG', 'LPG', 'Electric'], dtype='object')
Index(['Manual', 'Automatic'], dtype='object')
Index(['First', 'Second', 'Third', 'Fourth & Above'], dtype='object')
Float64Index([5.0, 7.0, 8.0, 4.0, 0.0, 6.0, 2.0, 10.0, 9.0], dtype='float64')


In [436]:
for i in range(len(categorical_columns)):
    print((test_data_input[categorical_columns[i]].value_counts().index))

Index(['Mumbai', 'Pune', 'Coimbatore', 'Hyderabad', 'Kochi', 'Kolkata',
       'Delhi', 'Chennai', 'Jaipur', 'Bangalore', 'Ahmedabad'],
      dtype='object')
Index(['Diesel', 'Petrol', 'CNG', 'LPG'], dtype='object')
Index(['Manual', 'Automatic'], dtype='object')
Index(['First', 'Second', 'Third', 'Fourth & Above'], dtype='object')
Float64Index([5.0, 7.0, 8.0, 4.0, 0.0, 6.0, 10.0, 2.0], dtype='float64')


#       Label Encoding of Categorical Variables

In [437]:
from sklearn.preprocessing import LabelEncoder

In [438]:
label_encoded_columns = {}
label_encoders = {}
for i in range(len(categorical_columns)):
    label_encoders[categorical_columns[i]] = LabelEncoder()
    label_encoders[categorical_columns[i]] = label_encoders[categorical_columns[i]].fit(train_data_input[categorical_columns[i]])
    label_encoded_columns[categorical_columns[i]]  = label_encoders[categorical_columns[i]].transform(train_data_input[categorical_columns[i]])

In [439]:
label_encoders

{'Location': LabelEncoder(),
 'Fuel_Type': LabelEncoder(),
 'Transmission': LabelEncoder(),
 'Owner_Type': LabelEncoder(),
 'Seats': LabelEncoder()}

In [440]:
for k in label_encoders.keys():
    print(label_encoders[k].classes_)

['Ahmedabad' 'Bangalore' 'Chennai' 'Coimbatore' 'Delhi' 'Hyderabad'
 'Jaipur' 'Kochi' 'Kolkata' 'Mumbai' 'Pune']
['CNG' 'Diesel' 'Electric' 'LPG' 'Petrol']
['Automatic' 'Manual']
['First' 'Fourth & Above' 'Second' 'Third']
[ 0.  2.  4.  5.  6.  7.  8.  9. 10.]


In [441]:
label_encoded_columns

{'Location': array([ 9, 10,  2, ...,  6,  8,  5]),
 'Fuel_Type': array([0, 1, 4, ..., 1, 4, 1]),
 'Transmission': array([1, 1, 1, ..., 1, 1, 1]),
 'Owner_Type': array([0, 0, 0, ..., 2, 0, 0]),
 'Seats': array([3, 3, 3, ..., 6, 3, 3])}

In [442]:
train_data_categorical = pd.DataFrame(label_encoded_columns)

In [443]:
train_data_categorical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 5 columns):
Location        6019 non-null int64
Fuel_Type       6019 non-null int64
Transmission    6019 non-null int64
Owner_Type      6019 non-null int64
Seats           6019 non-null int64
dtypes: int64(5)
memory usage: 235.2 KB


In [500]:
train_data_label_encoded = pd.concat([train_data_categorical,train_data_input[numerical_columns]],axis=1)

In [501]:
train_data_label_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 10 columns):
Location             6019 non-null int64
Fuel_Type            6019 non-null int64
Transmission         6019 non-null int64
Owner_Type           6019 non-null int64
Seats                6019 non-null int64
Kilometers_Driven    6019 non-null int64
Mileage              6019 non-null float64
Engine               6019 non-null float64
Power                6019 non-null float64
No_Years             6019 non-null int64
dtypes: float64(3), int64(7)
memory usage: 470.3 KB


# Label Encoding Columns 

In [446]:
label_encoded_columns_test = {}
label_encoders_test = {}
for i in range(len(categorical_columns)):
    label_encoded_columns_test[categorical_columns[i]]  = label_encoders[categorical_columns[i]].transform(test_data_input[categorical_columns[i]])

In [447]:
test_data_categorical = pd.DataFrame(label_encoded_columns_test)

In [502]:
test_data_categorical.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 5 columns):
Location        1234 non-null int64
Fuel_Type       1234 non-null int64
Transmission    1234 non-null int64
Owner_Type      1234 non-null int64
Seats           1234 non-null int64
dtypes: int64(5)
memory usage: 48.3 KB


In [518]:
test_data_label_encoded = pd.concat([test_data_categorical,test_data_input[numerical_columns]],axis=1)

In [519]:
test_data_label_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1234 entries, 0 to 1233
Data columns (total 10 columns):
Location             1234 non-null int64
Fuel_Type            1234 non-null int64
Transmission         1234 non-null int64
Owner_Type           1234 non-null int64
Seats                1234 non-null int64
Kilometers_Driven    1234 non-null int64
Mileage              1234 non-null float64
Engine               1234 non-null float64
Power                1234 non-null float64
No_Years             1234 non-null int64
dtypes: float64(3), int64(7)
memory usage: 96.5 KB


In [521]:
model_xgb_le = xgboost.XGBRegressor(colsample_bytree=0.4,
                 gamma=0,                 
                 learning_rate=0.07,
                 max_depth=3,
                 min_child_weight=1.5,
                 n_estimators=500,                                                                    
                 reg_alpha=0.75,
                 reg_lambda=0.45,
                 subsample=0.6,
                 seed=42) 

In [535]:
train_data_label_encoded[ 'Mileage'] = train_data_label_encoded[ 'Mileage'].replace(0.0,18.0)

In [536]:
train_data_label_encoded[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']] = train_data_label_encoded[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']].apply(np.log)

In [538]:
scores = cross_val_score(model_xgb_le, train_data_label_encoded.values, price_logs, cv=5)

[19:40:18] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:40:19] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:40:20] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:40:21] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[19:40:22] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [542]:
scores

array([0.93928616, 0.92834294, 0.92176892, 0.9392839 , 0.93556708])

In [540]:
test_data_label_encoded[ 'Mileage'] = test_data_label_encoded[ 'Mileage'].replace(0.0,18.0)

In [541]:
test_data_label_encoded[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']] = test_data_label_encoded[['Kilometers_Driven', 'Mileage', 'Engine', 'Power']].apply(np.log)

In [543]:
xgb_model_label_encoded = model_xgb_le.fit(train_data_label_encoded.values, price_logs)

[19:41:36] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [544]:
Price_predictions = pd.Series(np.exp(xgb_model_label_encoded.predict(test_data_label_encoded.values)))

In [545]:
Price_predictions.shape

(1234,)

#                  Random Forest Model 1 

In [553]:
train_data_label_encoded.describe()

Location    Fuel_Type  Transmission   Owner_Type        Seats  \
count  6019.000000  6019.000000   6019.000000  6019.000000  6019.000000   
mean      5.619704     2.363017      0.714238     0.379465     3.258847   
std       2.955933     1.504939      0.451814     0.818458     0.840634   
min       0.000000     0.000000      0.000000     0.000000     0.000000   
25%       3.000000     1.000000      0.000000     0.000000     3.000000   
50%       6.000000     1.000000      1.000000     0.000000     3.000000   
75%       8.000000     4.000000      1.000000     0.000000     3.000000   
max      10.000000     4.000000      1.000000     3.000000     8.000000   

       Kilometers_Driven      Mileage       Engine        Power     No_Years  
count        6019.000000  5951.000000  6019.000000  6019.000000  6019.000000  
mean            2.373335     1.055273     1.991012     1.530140     6.641801  
std             0.070592     0.083916     0.046157     0.087826     3.269742  
min             1.637377     0.618584     1.453174     1.261928     1.000000  
25%             2.345081     1.003515     1.958461     1.471717     4.000000  
50%             2.386747     1.065201     1.989044     1.524113     6.000000  
75%             2.415754     1.114903     2.026210     1.594826     9.000000  
max             2.752852     1.504035     2.163229     1.844974    22.000000

In [555]:
pd.Series(price_logs).describe()

count    6019.000000
mean        1.825095
std         0.874059
min        -0.820981
25%         1.252763
50%         1.729884
75%         2.297573
max         5.075174
dtype: float64

In [559]:
# Import the model we are using
from sklearn.ensemble import RandomForestRegressor

In [560]:
# Instantiate model with 1000 decision trees
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)

In [561]:
scores = cross_val_score(rf, train_data_label_encoded.values, price_logs, cv=5)

/home/subramanyat/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:542: FutureWarning: From version 0.22, errors during fit will result in a cross validation score of NaN by default. Use error_score='raise' if you want an exception raised or error_score=np.nan to adopt the behavior from version 0.22.
  FutureWarning)


ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [ ]:
# Train the model on training data
rf.fit(train_features, train_labels);

#      TPOT Regression

In [565]:
from tpot import TPOTRegressor

In [566]:
tpot = TPOTRegressor(generations=5, population_size=50, verbosity=2)

In [ ]:
tpot.fit(X_train, y_train)

In [568]:
scores

array([-0.04539958, -0.06872512, -0.05038229, -0.0414901 , -0.03907188])

#   Auto Sklearn

In [580]:
automl = autosklearn.regression.AutoSklearnRegressor()

NameError: name 'autosklearn' is not defined